name: Verification de Pull Request

on:
  push:
    paths:
      - '.github/workflows/*.yml'
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Verifier le nom de la branche
        run: |
          if [[ $GITHUB_EVENT_NAME != 'pull_request' || \
                ${{ startsWith(github.event.pull_request.head.ref, 'feature/') }} || \
                ${{ startsWith(github.event.pull_request.head.ref, 'fix/') }} || \
                ${{ startsWith(github.event.pull_request.head.ref, 'release/') }} || \
                ${{ startsWith(github.event.pull_request.head.ref, 'hotfix/') }} || \
                ${{ startsWith(github.event.pull_request.head.ref, 'docs/') }} || \
                ${{ startsWith(github.event.pull_request.head.ref, 'refactor/') }} || \
                ${{ startsWith(github.event.pull_request.head.ref, 'experiment/') }} || \
                ${{ startsWith(github.event.pull_request.head.ref, 'chore/') }} || \
                ${{ startsWith(github.event.pull_request.head.ref, 'devops/') }} ]]; then
            echo "Nom de branche valide"
          else
            echo "Nom de branche invalide"
            exit 1
          fi

      - name: Verifier le Reviewer et l'Assignee
        run: |
          if [[ ${GITHUB_EVENT_PULL_REQUEST_REQUESTED_REVIEWERS:-null} != null && \
                ${GITHUB_EVENT_PULL_REQUEST_ASSIGNEES:-null} != null && \
                ${GITHUB_EVENT_PULL_REQUEST_LABELS:-null} != null ]]; then
            echo "Reviewer, Assignee et Labels selectionnes"
          else
            echo "Reviewer, Assignee ou Labels manquant"
            exit 1
          fi

      - name: Verifier la description
        run: |
          if [ -n "$GITHUB_EVENT_PULL_REQUEST_BODY" ]; then
            echo "Description presente"
          else
            echo "Description absente"
            exit 1
          fi
